baseURL = 'https://example.org/'
title = 'Bulsara'
theme = 'Bulsara-theme'

[params]
facebookLink = "https://www.facebook.com/bulsaratributoaqueen" 
instagramLink = "https://www.instagram.com/bulsaratributo/"